### ISSUE TITLE
video is undefined most of time

### ISSUE THREAD

**Issue by pardeepsingh12365** [talmobi/yt-search#10]
hello dev
60-70% time there is null result showing for us

**Comment by kleinesNugget** [comment]
Having the same issue, the object videos of the result returns []
Using the same search query multiple times eventually gives a proper search result

**Comment by talmobi** [comment]
halåj~

published v2.0.0 that should fix some of these issues, but i'm not sure it's not 100% backwards compatible but it's pretty close.

**Comment by pardeepsingh12365** [comment]
> halåj~
> 
> published v2.0.0 that should fix some of these issues, but i'm not sure it's not 100% backwards compatible but it's pretty close.

**Comment by pardeepsingh12365** [comment]
> > halåj~
> > published v2.0.0 that should fix some of these issues, but i'm not sure it's not 100% backwards compatible but it's pretty close.

Glad to hear
When will you published it bro ?

**Comment by talmobi** [comment]
Halåj,

It's already published, install it with: `npm install yt-search@latest`

**Comment by pardeepsingh12365** [comment]
> Halåj,
> 
> It's already published, install it with: `npm install yt-search@latest`

oo ye bro thats working good and return result 100%
now everything is good

can you provide your discord server invite link for future support please  ??
i will close it  after

**Comment by talmobi** [comment]
halåj~

glad it's working please feel free to contact and/or make issue if you have problems with the package.

I don't have a discord server im not really sure actually what it is ^^;;
