### ISSUE TITLE
Using with discord.js - undefined

### ISSUE THREAD

**Issue by abrichar** [talmobi/yt-search#11]
Hello, 

i have a issue when i use your module with discord.js.
Each time i try to use your function like that : 
`YoutubeStream.validateURL(args[1])`
(args[1] = "astronaute" for example.) 
It send me undefined in videos, list and playlist.

Could you help me ? 
Thanks !

Abrichar

**Comment by talmobi** [comment]
Have you tried the latest 2.0.1 version?

`npm install yt-search@latest`

Also I'm not entirely sure how you're using it, try using it like this:

```js
const yts = require( 'yt-search' )

yts( 'astronaute', function ( err, r ) {
  if ( err ) throw err
  console.log( r.videos )
  console.log( r.playlists )
  console.log( r.channels )
} )
```

**Comment by abrichar** [comment]
Hello, 

I'm sorry, i did not send you the right place of the code... my bad >< 
`const yts = require( 'yt-search' )

let result = yts( 'astronaute');
console.log(result.videos);
console.log(result.playlists);
console.log(result.channels);

It works for a moment and after it didn't.. Don't know why ><
Thanks

**Comment by talmobi** [comment]
You should be using the node-style callbacks. Or you could use async/await as promises are supported like so:

```js
let result = await yts( 'astronaute' )
console.log( result )
```

**Comment by talmobi** [comment]
Halåj, did you get it working?

**Comment by talmobi** [comment]
Any updates on this?

**Comment by talmobi** [comment]
closing as inactive
