### ISSUE TITLE
Playlist metadata by id - getting 400: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by chaos87** [talmobi/yt-search#13]
I tried several different playlist IDs but I always get 400 Bad Request, and the message says "Cannot read property 'split' of undefined".
I suspect a dependency changed which caused a regression?

**Comment by talmobi** [comment]
Halåj~

Published v2.1.2 that should fix this error.

`npm install yt-search@latest`

**Comment by chaos87** [comment]
Yes it's fixed.

Great job!
