### ISSUE TITLE
Video.url Shows up undefined

### ISSUE THREAD

**Issue by DaLLamaKing** [talmobi/yt-search#17]
yts(searchterm, function ( err, r ) {
            let video = r.videos;
            console.log(video.url);
            let Fvideo = video[0];
            let URL = Fvideo.url;
            return URL;
});
I want  to be able to see the video's url. How would I go about doing that since video.url is undefined? All help greatly appreciated.

**Comment by talmobi** [comment]
you are logging the `url` param of the array of videos ( that you have named `video` ), not any video object itself.

Try `console.log( Fvideo.url )` or `console.log( r.videos[ 0 ].url )`

**Comment by DaLLamaKing** [comment]
It gives me this error then:
console.log( r.videos[ 0 ].url );
                                 ^
TypeError: Cannot read property '0' of undefined
