### ISSUE TITLE
When i search thai song it will show this error

### ISSUE THREAD

**Issue by DearTanakorn** [talmobi/yt-search#2]
err :https://pastebin.com/vPZqFhQV
How to fix

**Comment by talmobi** [comment]
hey~

what song are you searching for? thank you~

**Comment by DearTanakorn** [comment]
All thai song
Ex. 
1. "คุกกี้เสี่ยงทาย"
2. "ฤดูใหม่"
3. "ลาลาลอย"

**Comment by talmobi** [comment]
thank you~ I can reproduce the error -- I'm looking into it

**Comment by DearTanakorn** [comment]
Thank you i am die already to fix it ;)

**Comment by talmobi** [comment]
hey, GitHub apparently auto closes issues when you reference them in a commit message with includes 'fixes' string.. anyway, you could fix it yourself by simply escaping your query before giving it to yt-search:

`var query = require( 'querystring' ).escape( "คุกกี้เสี่ยงทาย" )`

but I patched a fix to automatically escape it in v0.4.1 for you.

Does this fix your issue?

**Comment by DearTanakorn** [comment]
Ok i will try

**Comment by talmobi** [comment]
@DearTanakorn halåj~ did the new version work for you?

**Comment by DearTanakorn** [comment]
Yeah it working well thx for fixing

**Comment by talmobi** [comment]
@DearTanakorn great success~ thanks for letting me know~
