### ISSUE TITLE
Search return empty results

### ISSUE THREAD

**Issue by chaos87** [talmobi/yt-search#21]
Hi,

Since this morning searching items does not work anymore. Resultset is always empty.

`const yts = require( 'yt-search' )

yts( 'superman theme', function ( err, r ) {
  if ( err ) throw err

  const videos = r.videos
  videos.forEach( function ( v ) {
    const views = String( v.views ).padStart( 10, ' ' )
    console.log( `${ views } | ${ v.title } (${ v.timestamp }) | ${ v.author.name }` )
  } )
} )`

--> no output

**Comment by davipatricio** [comment]
Can repro.

**Comment by creeking** [comment]
Having the same issue

**Comment by Jpufff** [comment]
can reproduce

**Comment by Jayy** [comment]
Can reproduce.

**Comment by brunogomes98** [comment]
Same problem

**Comment by RubberArchind** [comment]
Same here

**Comment by rajaie1976** [comment]
hi since 6 hours search is not working , it is showing this error in debug
TypeError: Cannot read property 'userAgent' of undefined
at /node_modules/yt-search/dist/yt-search.min.js:1:1702)

**Comment by talmobi** [comment]
I can reproduce, working on a fix.

**Comment by talmobi** [comment]
Published new patched version that should fix the issues: `yt-search@2.1.9`

`npm install yt-search@latest`

**Comment by vikram-sapate123** [comment]
Thanks @talmobi 🙂🙂🙂🙂🙂.
npm install yt-search@latest

**Comment by davipatricio** [comment]
Thanks!

**Comment by chaos87** [comment]
Thanks @talmobi!

**Comment by isuckatprogram** [comment]
Oh thanks! I'll update my package!
