### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by junehua1980** [talmobi/yt-search#27]
I search "王菲"，console show TypeError: Cannot read property 'split' of undefined.
like "王菲", "菲王", "王非", "非王" still show TypeError.
but search "王" or "菲" is ok.

**Comment by talmobi** [comment]
Should be fixed in `yt-search@2.2.3`

`npm install yt-search@latest`

Thanks for the issue report!

**Comment by junehua1980** [comment]
ok, it's working, thanks.
