### ISSUE TITLE
no video results found

### ISSUE THREAD

**Issue by healzer** [talmobi/yt-search#28]
As of today the yt-search module no longer works (including for many of my users).
To reproduce I am using the "easy to use" code snippet from here https://www.npmjs.com/package/yt-search
The array of videos is simply empty for any keyword.

I haven't dug deeper into the root cause, maybe someone already has an answer?

**Comment by talmobi** [comment]
Halåj~

Which version of `yt-search` are you using? Try updating with `npm install yt-search@latest`

Recently YouTube changed the way it serves pages that broke some of the parsings in earlier versions.

**Comment by Clydeston** [comment]
Can confirm this fix resolved my issue 👍
