### ISSUE TITLE
Live not an option

### ISSUE THREAD

**Issue by fbagjug** [talmobi/yt-search#29]
Hello once again xD. You recently updated the library to not have live streams in the video results but when I attempted to get the new option 'live' it doesn't appear to be there on version 2.2.4.

Edit: Upon further testing and research it appears that it's just not auto filling.

**Comment by talmobi** [comment]
Halåj~

Live stream results are rare unless you put "live" in the search query.

In most cases it will probably be empty as they would not usually show up on a youtube search first page results.

Is this the problem you are having?

**Comment by fbagjug** [comment]
The problem I was having was that the function 'live' wasn't auto filling in my IDE which made me think it was implemented weirdly which I can work around. My only thing now is that I have to figure out how to join both videos and live results filtered by views/viewers because I want both live and video results to show up and for the system to choose the prioritised one (which is usually live streams)

**Comment by talmobi** [comment]
The results aren't completely identical. As the live results don't have duration information for example. But live stream results have the "watching" field which should tell you the amount of viewers.

Usually the views are much larger than the amount watching so the live streams would fall to the bottom.

```javascript
async function m1 () {
	const r = await yts( 'minecraft' )
	const combined = (
		r.videos.concat( r.live )
		.sort( function ( a, b ) {
			return (
				( b.views || b.watching ) - ( a.views || a.watching )
			)
		} )
	)
	console.log( combined )
}
```

or if you want to keep the live results on top:

```javascript
async function m1 () {
	const r = await yts( 'minecraft' )
	const combined = (
		r.live.concat( r.videos )
	)
	console.log( combined )
}
```

**Comment by fbagjug** [comment]
Before you updated it for live streams to not be in with the videos did you put them on the top yeah?

**Comment by talmobi** [comment]
Before the update they would show up in the same order as they were displayed on the youtube page.

So most of the time I guess they would be on top? Not sure. Usually live streams appear at the top I think, if any are found.

Would you want to get the results in the same order as they were given in the youtube search results? Perhaps I could add that, then you could yourself filter for which type you want and still preserve the order.

**Comment by fbagjug** [comment]
Nope it's all good thanks :D I instead will just use the bottom concat method to filter the streams to the top

**Comment by talmobi** [comment]
Added new result property `r.all` in `yt-search@2.3.0` to get a combined list of all parsed results in the order that they appear.
