### ISSUE TITLE
Results come back as undefined

### ISSUE THREAD

**Issue by Misha2win** [talmobi/yt-search#30]
I am using similar code to the easy to use section (https://github.com/talmobi/yt-search#easy-to-use)
However each time it returns the results, they come back as undefined..
I made sure I am using the latest version of yt-search, using 'npm install yt-search@latest'
Is there any way to solve this?

**Comment by talmobi** [comment]
Can you paste the code you are using? Tests are passing for me. Thanks~

**Comment by talmobi** [comment]
closing as inactive
