### ISSUE TITLE
Versioning scheme?

### ISSUE THREAD

**Issue by D3SOX** [talmobi/yt-search#31]
Hi,

First of all: Nice project, thanks for your work. 
Working good so far but I have one question:

What is your versioning scheme?
If you don't have one, I would strongly suggest using [Semantic Versioning](https://semver.org/)

**Comment by talmobi** [comment]
Hello there,

Should be adhering to Semantic Versioning already.

Thanks~

**Comment by D3SOX** [comment]
Okay, but in version 2.2.0 with the commit https://github.com/talmobi/yt-search/commit/d1831f0f4e605e6594bb9616f00170c270b08923 you introduced a breaking change so that live streams are no longer included in `result.videos`.
Therefore, you should've increased the `MAJOR` version.

**Comment by talmobi** [comment]
Live streams were never supposed to show up in video results. Related issues: https://github.com/talmobi/yt-search/pull/23 https://github.com/talmobi/yt-search/issues/24

Therefore this was not a breaking change in my opinion.

Live streams is a new thing in YouTube and haven't always showed up in search results when for example this library was created.

This was a PATCH to remove live streams from video results and a MINOR to add live streams into a separate category.

Thanks~

**Comment by D3SOX** [comment]
Oh, okay. Sorry for the confusion and thanks for the explanation. Have a nice evening!

**Comment by talmobi** [comment]
Not at all. In software sometimes long standing bugs become features themselves that users rely on. It happens.

Have a good one~
