### ISSUE TITLE
Results are undefined

### ISSUE THREAD

**Issue by ZyorYT** [talmobi/yt-search#34]
I've tried this package and other ones but there all returning undefined/no results.
Did youtube update there api or is this part of that youtube download thingy thats going arround on the news.

**Comment by talmobi** [comment]
Hello there,

Can you give a small sample of the code you are using? The tests seems to be mostly passing.

There may be an inconsistency issue related to specifically single video and playlist metadata that I'll continue investigate.

Thanks~

**Comment by talmobi** [comment]
In other words, no relevant YouTube changes seems to have happened.

Also the inconsistency with video and playlist metadata should have been fixed in 2.4.2 just released.

Concerning the "youtube download thingy" no changes looks to have happened other than the `ytdl` repository being removed from github. It's still working and available on npm. You can also use something like `mpv` to stream/download youtube videos.

**Comment by ZyorYT** [comment]
```ts
import { Client, Message, MessageEmbed } from "discord.js";
import { OptionsCustom } from "../../bot";

module.exports = {
  name: "ytsearch",
  description: "Search for videos on youtube!",
  aliases: ["youtubesearch", "searchyoutube", "yts"],
  usage: "ytsearch",
  category: "General",
  run: async (bot: Client, message: Message, args: Array<String>, prefix: String, options: OptionsCustom) => {
    if (!args[0]) return message.channel.send(`Uhmmm.. You need to provide a video name to search for!\n${prefix}ytsearch <name>`);
    const yts = require('yt-search');
    console.log(await yts(args[0]));
  }
};```

**Comment by ZyorYT** [comment]
also im not trying to download youtube videos, I only want search results

**Comment by ZyorYT** [comment]
i dont want to get in trouble :P

**Comment by ZyorYT** [comment]
oh btw, you might see that I used require, I did try with import but it still didnt work

**Comment by talmobi** [comment]
Which version of `yt-search` are you using?

Try installing the latest version `npm install yt-search@latest`

Perhaps the `args[0]` variable you feed into the `yts` function is invalid? empty? very long?

**Comment by ZyorYT** [comment]
args[0] returns a perfectly fine string when used
and yes, I am using the latest version

**Comment by talmobi** [comment]
I'm not able to reproduce your error. Try using it outside of your discord bot to see if it work using a simple example in the README. I can only speculate it's an issue with your code somewhere.

**Comment by ZyorYT** [comment]
ok

**Comment by ZyorYT** [comment]
i figured out the issue, it was my "project". I made a new "project" and it works now

**Comment by talmobi** [comment]
Thanks for the update!

**Comment by jsdevv** [comment]
👍
