### ISSUE TITLE
I might be doing something wrong.

### ISSUE THREAD

**Issue by AzSa5z1n** [talmobi/yt-search#4]
Searching for "Josh A & Jake Hill - Rest in Pieces (Lyrics)" or just the url itself "https://www.youtube.com/watch?v=_JzeIf1zT14" Will not find this video. Usually searching for a url puts it in the top 1-3 spots but this url doesn't work. I am not sure how to detail this or why this happens.

These URLs as well:
https://www.youtube.com/watch?v=_G6pGZJiCi8
https://www.youtube.com/watch?v=_P5P4_ISofI
https://www.youtube.com/watch?v=_X3qw3ytgTg  // Provides nothing.
![image](https://user-images.githubusercontent.com/26307955/71861121-41dd4e80-30c3-11ea-9af0-a109b27e8f1b.png)

I am using the global version for them and my locally installed version and both are sending the same information.
Seems to be urls with the ID starting with '_'(underscore).

**Comment by talmobi** [comment]
Hello

Thanks for submitting the issue. I did indeed see that the order of the results did not match that of what you would expect, they were sorted by node-fzf internally for no good reason. That package has been patched and the order should now be as expected!

Searching by full URL is a bit inconsistent and I only found a few urls turned some results ranging form 0-2. If you search by the video id (ex. _4Vt0UGwmgQ) instead the results should now be as expected ( top result the video url with that video id ).

I polished up some cross-language duration parsing and added more tests.

Please try the new version to see if it works as expected `yt-search@0.4.5`

`npm install -g yt-search@latest`

The full URL (ex: https://www.youtu...) search does not always give results when you search for it on youtube either, so I don't think that's an issue. I want to mimic the way youtube would give you the results as if you were on their website as much as possible.

**Comment by AzSa5z1n** [comment]
I understand! This makes it a little complicated for making sure that the url matches so I have my code like this 
![image](https://user-images.githubusercontent.com/26307955/71869541-70b5ed80-30e0-11ea-899c-672f21ced13f.png)
And everything seems to be working perfectly thank you so much.
![image](https://user-images.githubusercontent.com/26307955/71869610-b07cd500-30e0-11ea-9140-7e9d4de6e308.png)

**Comment by talmobi** [comment]
I see you're using it to get a specific video's metadata like title or duration etc?

I might add an option to the API to only get a single video's metadata like the way you are using it.

Thanks for sharing.

Also this module may be related to your interest ( I don't know if it works ): https://www.npmjs.com/package/youtube-info

**Comment by AzSa5z1n** [comment]
> I see you're using it to get a specific video's metadata like title or duration etc?
Yes, and for an array of videos 10 at a time. If the url or ID are a match/valid it will use that one. If it is not valid it will list an array of videos you might be looking for.
ytdl-core can already do this except for it doesn't give a timestamp or time_seconds.

As for the second package `youtube-info` I was using that before, however you have the information listed exactly how it should be. Their information is a little more modular and you have to format it yourself causing some code to look very messy and react very slowly.

I am still looking for a way to parse playlists and get the video information for everything in the playlist without the `google api key` for `youtube api v3` If you know how to do that or want to help at all you can contact me on discord. AzSa5z1n#8793 or post here if you'd like,

**Comment by talmobi** [comment]
Hey,

Working on these now. Have single video search done and going to tackle playlists next. Some refactoring and changes to to previous search result parsing too but shouldn't be any breaking changes; only additions.

Most likely minor version update with these changes tomorrow.

**Comment by talmobi** [comment]
@AzSa5z1n 

Bumped major version (1.0.0) as there were quite a lot of changes and some breaking changes ( full http urls now included in results instead of partial urls ).

`npm install yt-search@1.0.0`
`npm install yt-search@latest`

You can try the new version with getting video metadata by id:
https://github.com/talmobi/yt-search#video-metadata-by-id

or playlist metadata by id:
https://github.com/talmobi/yt-search#playlist-metadata-by-id

Tried to grab and provide as much data as was available on those pages, anything more might require a headless browser.

**Comment by AzSa5z1n** [comment]
I will get right on that thank you. I had manually gotten a lot done so I am going to make a new project and test everything out with the urls and requests that I have saved that returned weird information before and try out the playlists.

**Comment by AzSa5z1n** [comment]
So far everything seems to run perfectly except for the 'metadata by id'

> Video metadata by id
const yts = require( 'yt-search' )
const opts = { videoId: 'e9vrfEoc8_g' }
yts( opts, function ( err, video ) {
  console.log( video )
} ) // This is your example.

`{ videoId: "_JzeIf1zT14" }` or `{ videoId: "-RcuLY-11ho" }` 
These are IDs I know for sure do not return results. I would have more but I am just testing an array of IDs and if it fails it doesn't return the ID to me.
I ran a few playlists of video IDs through this function and a lot of the time I get this error:
![image](https://user-images.githubusercontent.com/26307955/71982256-042b1380-31f2-11ea-8e59-b8db3ef774af.png) I could bypass this with by not searching with the videoId like I did before but I thought you might like to know.

Previously I had away around those links that did not work with this method:
![image](https://user-images.githubusercontent.com/26307955/71982661-02ae1b00-31f3-11ea-8219-1a5bdd451e57.png) I am only showing this again in full this time, incase it can help you fix some IDs not working.

This is also how your CLI displays the https links after your update:
![image](https://user-images.githubusercontent.com/26307955/71982466-861b3c80-31f2-11ea-906d-62f7ae8df12b.png)

The playlist information is great and that all seems to work well. After a few hundred listings I haven't had any errors.

**Comment by talmobi** [comment]
Thanks for testing!

Just published 1.0.1 with fixes to what seems like all of these.

I opted to not add `www.` to the url's as it doesn't seem to be necessary but the CLI did indeed double it up incorrectly which is now fixed.

**Comment by AzSa5z1n** [comment]
I have noticed the update just super busy. Thanks for the updates. I am fairly new to js so I do apologize if anything's working and I'm just incompetent. I have tried to make sure information was correct.

**Comment by talmobi** [comment]
Not at all take your time you've been of great help. Thank you very much~

**Comment by AzSa5z1n** [comment]
The same function I was using yesterday works 80% faster.

My code:
> var args = `https://www.youtube.com/playlist?list=PLhf_RSaUvUVvuJHpeiTvnk5n99rlRM-tV`;
if (args.includes("playlist?list=")) {
  const listInfo = { listId: args.split("playlist?list=")[1] };
  ytSearch(listInfo, function(error, list) {
    if (error) throw error;
    const video = list.items;
    video.forEach(function(l) {
      const videoInfo = {
        videoId: l.url.split("&list=")[0].split("watch?v=")[1]
      };
      ytSearch(videoInfo, function(error, v) {
        if (error) throw error;
        console.log(v);
      });
    });
  });
}

Currently I do not check and make sure that the listId = 34 characters // This matters later.

Every once in a while I get an error like this one:
![image](https://user-images.githubusercontent.com/26307955/72038322-02536580-326f-11ea-9522-a13966e8ed29.png) It seems to only happen if I list the entire video array and not when I list:
(ex. `v.title`) Another thing that may or may not contribute to this error is that the playlist items seem to be randomized video order every time.

I was wondering if you could help me with one thing that I am not sure of. When I run this function and the arguments are valid everything works great. So now I wan't to pass through an invalid listId for example:
> var args = `https://www.youtube.com/playlist?list=XLhf_RSaUvUVvuJHpeiTvnk5n99rlRM-tV`;
This brings you to "https://www.youtube.com/oops".

All I did was change the listId to start with an "X" instead of "P" so this is now an invalid listId. Doing this in the function causes this error:
![image](https://user-images.githubusercontent.com/26307955/72038758-7f330f00-3270-11ea-82cc-bdb80c5cfe8f.png)

Do you know how I can catch these errors? For example `if (error) return console.log('Invalid listId')`?

**Comment by talmobi** [comment]
Thank you very much for the detailed information.

I've now added a few fallbacks for some of the things that might have caused errors such as with the JSON parsing.

I also now specifically handle faulty/missing listId or videoId's by returning an error in the callback's first argument.

Also I now capture all DOM parsing errors internally and pass them to the first parameter of the callback function.

So invalid listId's should return a `http status: 303` error (or something similar) and invalid videoId's should return `video unavailable` errors.

All other errors will be passed in their original forms to the callback also.

Also when getting the video id's from a playlist you should be able to use `item.videoId` instead of parsing it from the `item.url`

**Comment by talmobi** [comment]
Forgot to say, published new version 1.0.2 to npm.

**Comment by AzSa5z1n** [comment]
It catches the errors now! Thank you so much.

**Comment by talmobi** [comment]
Great! Thanks for helping out. Hopefully it works out. Feel free to report any issues you come across in the future~

**Comment by AzSa5z1n** [comment]
Question: Is it possible to get more than 100 videos from a playlist? It seems like yt-search only pulls 100 videos max instead of the max size of a playlist.

I have not had any issues so far since the most recent patch.

**Comment by talmobi** [comment]
Hey,

Can you give me the id of the playlist you're trying to get?

**Comment by AzSa5z1n** [comment]
PLMFoDoF5WCjivNyZjSOWfzjD4TyFbvqhu

I have another request. In thumbnail can you change it so it grabs hq720.jpg if it exists instead of hqdefault.jpg.

**Comment by talmobi** [comment]
It may be possible. I noticed the scrolling issue when searching for normal videos. It basically only grabs the first page results because every other page has the same videos until you scroll down on the page.

The scrolling down request looks like it should be easily reproducible (ex. you can see it in the network tab in chrome where you can replay it or copy it).

The playlists may use a similar approach.

Not sure yet what to do about this. Would like to be able to grab at least a few pages/scrolls worth of videos.

This module is originally intended for simple queries. If you need advanced use-cases you should really look into YouTubes own API where it provides you with all the things.

I want to look into it but have no timeline for it right now.

**Comment by AzSa5z1n** [comment]
That's fine I was just curious and didn't know how else to ask but here. Youtube API can do all of the videos but you can only request so much per day and in my discord I get the request limit almost every few hours. All good though thank you!

**Comment by talmobi** [comment]
@AzSa5z1n 

FYI the creator of `ytdl-core` has also made https://github.com/TimeForANinja/node-ytsr and `node-ytpl` that seem to work pretty well -- I will probably incorporate some of the things I learn from his code into this module. Particularly the nextPageResults that are currently not working in this module.
