### ISSUE TITLE
How to solve this error when trying to update this packages

### ISSUE THREAD

**Issue by BlazeDexX** [talmobi/yt-search#41]
![image](https://user-images.githubusercontent.com/67855694/104875612-44d27680-5988-11eb-93ec-7e78bed3a97b.png)

**Comment by talmobi** [comment]
Hello there,

Try deleting the `node_modules` directory and reinstalling.

```
rm -rf node_modules
npm install
npm install yt-search
```

**Comment by BlazeDexX** [comment]
> Hello there,
> 
> Try deleting the `node_modules` directory and reinstalling.
> 
> ```
> rm -rf node_modules
> npm install
> npm install yt-search
> ```

has solved, thanks for response.
