### ISSUE TITLE
`videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` instead.

### ISSUE THREAD

**Issue by vikram-sapate** [talmobi/yt-search#42]
How to remove this warning `videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` ?????? 
Each time I use yt-search , this warning is coming on console.

**Comment by talmobi** [comment]
Hello there,

Which version are you using?

I can't seem to find any similar/relevant strings in the git history using `git log -S --all`, but I do seem to recall having some deprecation warnings at some point.

**Comment by vikram-sapate** [comment]
yt-search@2.5.2

**Comment by talmobi** [comment]
Hello there,

I'm not able to reproduce. Can you create a small example that reproduces this issue?

Also try deleting your `package-lock.json` file and `node_modules` directory and re-installing.

**Comment by vikram-sapate** [comment]
Thanks, it is working now.
