### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by D-cat1** [talmobi/yt-search#48]
error when using plalylist with id

id playlist : PLSwcuYF4r6MJHkUVYbDAekT7j0FvZ_B4X

**Comment by talmobi** [comment]
Hello there~

Thank you. The issue was that playlist's with "no views" were crashing the parser. This has been fixed in just released patch `2.7.2`.

`npm install yt-search@2.7.2`

**Comment by D-cat1** [comment]
Hi! I found the error again in playlist id : PLQ9SiFtEqtYByscXDLGNOC8XL49BFn9tZ
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'slice' of undefined

**Comment by talmobi** [comment]
Good catch. Should be fiixed in `2.7.3`
