### ISSUE TITLE
search throws http 302 and returns undefined

### ISSUE THREAD

**Issue by LordFarquhar** [talmobi/yt-search#53]
When using yt-search#search, it throws this string as an error "http status 302" (NOT as an error object)

**Comment by talmobi** [comment]
Hello there, thanks for the report.

Youtube seems to have changed/added something to their redirecting scheme which broke auto follow redirects.

Should be fixed in patched version `2.7.6`

`npm install --save yt-search@2.7.6`

**Comment by LordFarquhar** [comment]
Wonderful, thank you for the quick response.
I shall update that and test it right away!

**Comment by LordFarquhar** [comment]
Works perfectly as expected
Thank you for the quick response and the wonderful package. Keep up the amazing work

**Comment by karimmakhloufi** [comment]
Works great, thanks !
