### ISSUE TITLE
Vulnerability issue for yt-search for discord bot

### ISSUE THREAD

**Issue by FRG-SHADOWFALL** [talmobi/yt-search#58]
Denial of service

**Comment by talmobi** [comment]
Which discord bot? Any more information?

This is a library/module.

**Comment by scxipted** [comment]
I believe you're referring to this https://www.npmjs.com/advisories/1754?

**Comment by talmobi** [comment]
I see.

`css-what` is a dependency of `cheerio`, which is used to parse the html from youtube.

Given that we're parsing youtube pages only, I'm not concerned too much of DOS attacks.

I'll put it on the TODO list.

**Comment by FRG-SHADOWFALL** [comment]
thx

**Comment by FRG-SHADOWFALL** [comment]
yes i am how do i possibly fix it?

**Comment by talmobi** [comment]
try updating css-what, might work

**Comment by scxipted** [comment]
Didn't seem like it worked.

**Comment by cktang88** [comment]
Updating `cheerio` to at least https://github.com/cheeriojs/cheerio/tree/v1.0.0-rc.6 will probably work, which has the updated `css-what` lib

**Comment by talmobi** [comment]
> Updating `cheerio` to at least https://github.com/cheeriojs/cheerio/tree/v1.0.0-rc.6 will probably work, which has the updated `css-what` lib

you want to make a PR with updated dependencies?

**Comment by talmobi** [comment]
Should be fixed with cktang88's PR merged and published to 2.9.0

**Comment by cktang88** [comment]
works fine on new proj now 
![image](https://user-images.githubusercontent.com/10319942/122656561-41067400-d121-11eb-8081-e4a2f810abef.png)

**Comment by talmobi** [comment]
@cktang88 thanks for the PR and looking into it, will leave this open for ~30 days or when @FRG-SHADOWFALL confirms it solved his issue and closes it himself

**Comment by FRG-SHADOWFALL** [comment]
Thanks a lot to who ever helped in fixing the issue it has been resolved now !
AND GOOD LUCK WITH SOLVING OTHER ISSUES ! :)
