### ISSUE TITLE
cannot add hl settings to a single playlist

### ISSUE THREAD

**Issue by CatsMiaow** [talmobi/yt-search#60]
https://github.com/talmobi/yt-search#single-playlist
```ts
const list = await yts({ listId: 'PLmtapKaZsgZt3g_uAPJbsMWdkVsznn_2R', hl: 'any' });
```
I want to add language settings like above.

https://github.com/talmobi/yt-search/blob/107116a54b70e16ca25659e8becd71a31512bc58/src/index.js#L1048-L1050
The `hl` and `gl` parameters are fixed in the source, can I change them?

**Comment by talmobi** [comment]
Ah, yes the options.hl and options.gl are only grabbed for search results, but not for single video or playlist metadata.

https://github.com/talmobi/yt-search/blob/master/src/index.js#L275-L276

I will have to add that.

**Comment by CatsMiaow** [comment]
Fixed https://github.com/talmobi/yt-search/pull/61
