### ISSUE TITLE
Search limit

### ISSUE THREAD

**Issue by Mimexe** [talmobi/yt-search#64]
Hello, is it possible to set a search limit. Example: `const r = await yts("superman theme", {max: 5})`

**Comment by talmobi** [comment]
No because it would not make sense because you get all the results from the first load (it would not affect bandwidth or efficiency or anything like that).

You can limit it yourself afterwards easily enough 💪 if you want to~

**Comment by Mimexe** [comment]
I found it's .slice(0, 5)
