### ISSUE TITLE
Protocol mismatch. Expected: http:. Got: https 

### ISSUE THREAD

**Issue by Landris18** [talmobi/yt-search#72]
I'm using bun runtime but not nodeJS and I have this error:

![image](https://user-images.githubusercontent.com/47665507/225969572-da930b60-8ae9-408a-b64b-a687161f60f7.png)

**Comment by talmobi** [comment]
@Landris18 hope you got it sorted, I'm not sure I have time to look into this.

**Comment by Landris18** [comment]
@talmobi , it's work well now , the problem was in bun 🙏
