### ISSUE TITLE
Banned dependency

### ISSUE THREAD

**Issue by SpaceGaint** [talmobi/yt-search#74]
I used yt-search in my app and deployed my app in [railway](railway.app) and I got an error:

Banned dependency
- yt-search

I don't know why they banned but I want to know is there any fix for this.
Thank You!

**Comment by talmobi** [comment]
@SpaceGaint hello

You can try copy pasting the source code of `yt-search` directly into your local project.

You can also try using an alternative similar package: https://github.com/TimeForANinja/node-ytsr

**Comment by talmobi** [comment]
oh and i've no idea why it's banned -- the samples still work fine in runkit that are linked in the README -- never heard of railway before either but i'm not up-to-date with latest of web dev tech at the moment

**Comment by talmobi** [comment]
@TimeForANinja hello, any details for why your project https://github.com/TimeForANinja/node-ytsr was deprecated? thanks~

**Comment by SpaceGaint** [comment]
> @SpaceGaint hello
> 
> You can try copy pasting the source code of `yt-search` directly into your local project.
> 
> You can also try using an alternative similar package: https://github.com/TimeForANinja/node-ytsr

The js code is too long to copy, Its showing failed to copy. If you don't mind, could you please make a gist of js code for me?

**Comment by talmobi** [comment]
@SpaceGaint ... figure it out, buddy -- what you just said makes very little sense

**Comment by TimeForANinja** [comment]
@talmobi simply don't have the time to maintain it
