### ISSUE TITLE
videoId is undefined sometimes

### ISSUE THREAD

**Issue by KareemH** [talmobi/yt-search#9]
Hello, I am using a music artist name + song + "official music video" as the search query to yts. I understand that I have to access the video property of the results object, and index to the first element

Some songs are able to scrape the videoId and thumbnail, while some songs cannot. I don't think I am able to replicate which songs are causing this error since I am looping through 220 songs.

![image](https://user-images.githubusercontent.com/40571613/80546884-cad70900-8984-11ea-8a58-b7122f86dc87.png)

I am storing this data onto a database, so videoId and coverImage are fields that are populated when I scrape data from your API

This is my code (artist and title work fine):
![image](https://user-images.githubusercontent.com/40571613/80546924-ec37f500-8984-11ea-8d64-2880a5230c30.png)
![image](https://user-images.githubusercontent.com/40571613/80546934-f0641280-8984-11ea-9479-f916cbc88ae5.png)
![image](https://user-images.githubusercontent.com/40571613/80546942-f5c15d00-8984-11ea-86cf-ab087e976d2b.png)

Thank you for any clarification

**Comment by talmobi** [comment]
It seems the html parsing is failing for some for some reason. Do you have a sample list of which 220 songs you are querying?

I could run a loop to find out which ones are failing and dig deeper.

**Comment by TheSpartaPT** [comment]
this might be the same problem as the one I'm having, if so it's not a specific video that's causing the issue, the issue happens randomly, sometimes it works sometimes it doesn't with the exact same query.

here's a trace of the issue I'm having:
![image](https://user-images.githubusercontent.com/8343238/81730557-9fc0df00-9485-11ea-98b8-9fbcd614e159.png)
![image](https://user-images.githubusercontent.com/8343238/81730920-2a094300-9486-11ea-9fd4-5ac9bf495d0f.png)

**Comment by ElectricReality** [comment]
I dont know if this helps but my workaround with this is retrying for a couple of times the search until a result pops up. Here's my code:

```js
let tracks = "";
  
  let i = 0
  while (true) {
    console.log(tracks)
    if (tracks.length == 0) {
      tracks = await music.getTracks(query); // the function i call to get the search result
    } else {
      break
    }
    if(i == 10){
      console.log('breaking search chain')
      break
    }
    i++
  }
```

**Comment by KareemH** [comment]
So I am using the billboard top songs npm package: https://www.npmjs.com/package/billboard-top-100

And I am looping through the top 20 songs of each year based on the current day, sort of like this:
![image](https://user-images.githubusercontent.com/40571613/82157455-8508b480-984f-11ea-939c-1bd8aa1065a2.png)
For resolved date, just add today's date for now as the second parameter to the getChart functon. In the addSong function, this is where I make the call to your api. So you don't have to have an addSong function, just use:
![image](https://user-images.githubusercontent.com/40571613/82157500-d022c780-984f-11ea-832d-a1da170923b7.png)
as your two parameters for a youtube search (the artist and title of the song)

**Comment by talmobi** [comment]
halåj~

published v2.0.0 that should fix some of these issues, but i'm not sure it's not 100% backwards compatible but it's pretty close.

**Comment by talmobi** [comment]
Any updates on this?

**Comment by Trinity7even** [comment]
@talmobi I got same issue too
code:
```
yts(Msgcontent, function(err, video){
  target = video.videos[0];
  if(target != undefined){
    title = target.title;
    url = target.url;
    ytdlInfo(url, user, message);
    message.channel.send(title + " has been added");
  }
})
```
console:
```
                 console.log(target.videos[0]);
                                   ^

TypeError: Cannot read property 'videos' of undefined
    at C:\Users\True_Administrator\Documents\Bots\Music\index.js:255:36
    at C:\Users\True_Administrator\Documents\Bots\Music\node_modules\yt-search\dist\yt-search.min.js:1:7633
    at i (C:\Users\True_Administrator\Documents\Bots\Music\node_modules\dasu\dist\dasu.min.js:1:4230)
    at Gunzip.<anonymous> (C:\Users\True_Administrator\Documents\Bots\Music\node_modules\dasu\dist\dasu.min.js:1:2689)
    at Gunzip.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

And, there is somethin strange - if I trying console.log(video) - it works

**Comment by talmobi** [comment]
Hey @Trinity7even 

Can I see more of the code?

The variables don't seem to be defined so there might be some global leaking going on and also you are not checking the `err` object for possible errors.

Are you consistently getting the error or just some of the time? What search term are you seeing the error on?

**Comment by Trinity7even** [comment]
@talmobi It's was a part of separated command in my discord bot. There is a full code of that.
```
}else if (message.content.startsWith(Prefix + `play`)){            
            let msg = message.content;
            let url
            let user = message.author.id;
            let Msgcontent = String(cut(msg, message));
            let title;
            let target;
            

              yts(Msgcontent, function(err, video){
                target = video.target.videos[0];
                if(target != undefined){//Not playlist
                  title = target.title;
                  url = target.url;
                  ytdlInfo(url, user, message);
                  message.channel.send(title + " has been added");
                }else{//playlist
                  target = video.playlists[0];
                  countVideo = target.videoCount;
                  title = target.title;
                  url = target.url;
                  message.channel.send("playlist **" + title + "** added to queue");

                  ytlist(url, 'url').then(res => {

                    for  (var key in res.data.playlist){
                      
                      url = res.data.playlist[key];
                
                      ytdlInfo(url, user, message);
                        
                    }
                  });
                }
              })
}
```
function cut() return text from command, without command itself. I checked, it works correct, with url directly too

> Are you consistently getting the error or just some of the time? What search term are you seeing the error on?
When I trying to get info by request from command. It can be url or txt, to video or playlist, nvm, its drops error at any case of this.
But, when I tested yts() with only url as argument - it works. And, it still works at console.log

**Comment by Trinity7even** [comment]
upd.
I checked it in other, simple command and got that
```
            let url = "https://www.youtube.com/watch?v=a1dFtEXCqaY&list=PLkU8l1ITH2CVk276SG7aWfsSrmlSzFtYw&index=2&t=0s"
            yts(url, function(err, video){

              console.log(video)
              console.log("2 " + video.videos[0])
              target = video.videos[0];
              console.log("3 " + target);

            })
```
Console:
```
{ videos: [],
  live: [],
  playlists: [],
  lists: [],
  accounts: [],
  channels: [] }
2 undefined
3 undefined
```
Probably, its my fault somewhere, bc I got the same issue with youtube-search

**Comment by talmobi** [comment]
The reason you are not getting results is because if you put that into the YouTube search box you also get no results:

![](https://i.imgur.com/0lRpG4u.png)

You can instead set the specific `videoId` or `listId` to search for a specific video or playlist.

Example:

```javascript
  const message = 'https://www.youtube.com/watch?v=a1dFtEXCqaY&list=PLkU8l1ITH2CVk276SG7aWfsSrmlSzFtYw&index=2&t=0s'

  // find video id in message (url)
  let match = message.match( /[?&]v=(\w+)&?/ )
  const videoId = match && match[ 1 ]

  // find list id in message (url)
  match = message.match( /[?&]list=(\w+)&?/ )
  const listId = match && match[ 1 ]

  // find list index specified in message (url)
  match = message.match( /[?&]index=(\w+)&?/ )
  const listIndex = match && match[ 1 ]

  if ( videoId ) {
    // found video id in url
    const opts = { videoId: videoId }
    const r = await yts( opts )
    console.log( r )
  } else if ( listId ) {
    // only a list id was found
    const opts = { listId: listId }
    const r = await yts( opts )
    console.log( r )

    // first video in playlist
    console.log( r.videos[ 0 ] )

    if ( listIndex ) {
      console.log( r.videos[ listIndex ] )
    }
  }
```

**Comment by Trinity7even** [comment]
@talmobi 
Yeah, its all bcs I put url instead title. I rechecked with that code:
```
            let url = "Nier: Automata - Bipolar Nightmare 【Intense Symphonic Metal Cover】"
            yts(url, function(err, video){

              console.log(video)
              console.log(video.videos[0])
              target = video.videos[0];
              console.log(target);

            })
```
and everything is alright.
But, when I check my main script - still doesnt work.
Code again:
```
            // let msg = message.content;
            let url
            let user = message.author.id;
            let Msgcontent = "Nier: Automata - Bipolar Nightmare 【Intense Symphonic Metal Cover】";
            let title;
            let target;
            

              yts(Msgcontent, function(err, video){
                target = video.videos[0];

                if(target != undefined){//Not playlist
                  title = target.title;
                  url = target.url;
                  ytdlInfo(url, user, message);
                  message.channel.send(title + " has been added");
                }else{//playlist
                  target = video.playlists[0];
                  countVideo = target.videoCount;
                  title = target.title;
                  url = target.url;
                  message.channel.send("playlist **" + title + "** added to queue");

                  ytlist(url, 'url').then(res => {

                    for  (var key in res.data.playlist){
                      
                      url = res.data.playlist[key];
                
                      ytdlInfo(url, user, message);
                        
                    }
                  });
                }
              })
```
console:
```
                target = video.videos[0];
                               ^

TypeError: Cannot read property 'videos' of undefined
    at C:\Users\True_Administrator\Documents\Bots\Music\index.js:254:32
    at C:\Users\True_Administrator\Documents\Bots\Music\node_modules\yt-search\dist\yt-search.min.js:1:7633
    at i (C:\Users\True_Administrator\Documents\Bots\Music\node_modules\dasu\dist\dasu.min.js:1:4230)
    at Gunzip.<anonymous> (C:\Users\True_Administrator\Documents\Bots\Music\node_modules\dasu\dist\dasu.min.js:1:2689)
    at Gunzip.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
So, its my bad, or something else? Commands are similar, moreover, its happend suddenly, and before everything was allright

**Comment by talmobi** [comment]
throw or console.log the `err` object to see what kind of error is showing up.

**Comment by Trinity7even** [comment]
@talmobi 
null, but Msgcontent is ok

**Comment by talmobi** [comment]
Which version of `yt-search` are you using? Try updating to the latest one `npm install yt-search@latest`

**Comment by Trinity7even** [comment]
@talmobi 
Yep, updating helped me. Thx very much!

**Comment by talmobi** [comment]
Yeah YouTube recently changed the way it is rendering pages so the previous way `yt-search` used to parse the content was sometimes failing. Glad it works.
